---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">
<div style="line-height: 1.5em;">
&nbsp;

### Working Papers

Evidence-based Decisions and Education Policymakers. **Job Market Paper.**

In today’s era of evidence-based policymaking, education policymakers face pressure to use research to inform their decisions. This paper explores the mental models that policymakers use when integrating research evidence in their policy decisions, with a focus on education policymakers working in state and local education agencies in the United States. First, I examine policymakers’ preferences for research evidence. Using a discrete choice experiment, I present policymakers with a series of research studies that vary along attributes of internal and external validity. I find that policymakers have preferences for larger studies and studies conducted in similar contexts as their own jurisdiction. However, they do not have a preference between experimental and observational studies. Second, I explore how policymakers update their beliefs about the effectiveness of education policies using an information experiment. I show that policymakers update their beliefs in response to research evidence, but these effects are large and persistent only when the information presented contains a brief, accessible explanation of how the evidence was generated. The results of my study have implications for the production of education research, training of education leaders, and communication of scientific evidence.

***

[Promoting Parental Involvement in Schools: Evidence From Two Randomized Experiments.](files/parenting_mexico.pdf)  
(with Barrera-Osorio, F., Gertler, P. & Patrinos, H.)

Parental involvement programs aim to strengthen school-home relations with the goal of improving children’s educational outcomes. We examine the effects of a parental involvement program in Mexico, which provides parent associations with grants and information. We separately estimate the effect of the grants from the effect of the information using data from two randomized controlled trials conducted by the government during the rollout of the program. Grants to parent associations did not improve educational outcomes. Information to parent associations reduced disciplinary actions in schools, mainly by increasing parental involvement in schools and changing parenting behavior at home. The divergent results from grants and information are partly explained by significant changes in perceptions of trust between parents and teachers. Our results suggest that parental involvement interventions may not achieve their intended goal if institutional rules are unclear about the expectations of parents and teachers as parents increase their involvement in schools.

***

[Long-run Effects of Short-term Grants in Early Childhood Education.](files/longrun_indonesia.pdf)

The expansion of early childhood education in developing countries has been supported by
project interventions, which provide subsidized programs for a fixed period of time, followed by the introduction of small user fees in order to sustain the programs. How do short-term subsidies affect preschool enrollment and fees in the long run? This paper uses data from Indonesia, where a three-year subsidy expanded access to early childhood education. Using a difference-in-differences design, I show that the short-term subsidy had long-term effects on raising preschool enrollment rates but no significant impacts on preschool fees. I conduct a survey experiment to test different demand-side mechanisms. The results are most consistent with learning effects: parents updated their beliefs about the benefits of preschool from increased access to them as a result of the short-term subsidy.

***

[Mama Knows (And Does) Best: Maternal Schooling Opportunities and Child Development in Indonesia.](files/mama_indonesia.pdf)  
(with Hasan, A. & Rangel, M.)  

This paper leverages quasi-experimental variation in increased access to basic formal education -- introduced by a large-scale school construction program in Indonesia in the 1970s -- to quantify the benefits to the children of women targeted by the program. Novel and rich data allow the analysis of a range of health, cognitive and socio-emotional outcomes for children. We find that increased maternal access to schooling has positive effects on children’s development along multiple developmental outcomes. We also explore pathways of these intergenerational effects. Mothers who were exposed to more schooling opportunities during childhood demonstrate less hostility toward their own children as parents and invest more in their own children’s preschool education.

*** 

### Peer-reviewed Publications

[Built to Last: Sustainability of Early Childhood Education Services in Rural Indonesia.](https://www.tandfonline.com/doi/full/10.1080/00220388.2021.1873283)   
(with Hasan, A., Jung, H., Kinnell, A., Maika, A. & Pradhan, M.)  
*The Journal of Development Studies*. 2021.
  
  + [Data & Code](https://github.com/nozominakajima/sustainability)

***  

[Contrasting Experiences: Understanding the Longer-Term Impact of Improving Access to Preschool Education in Rural Indonesia.](https://www.tandfonline.com/doi/full/10.1080/19345747.2020.1839989)   
(with Hasan, A., Jung, H., Kinnell, A., Maika, A. & Pradhan, M.)  
*Journal of Research on Educational Effectiveness*. 2021.

  + [Ungated version](files/twocohort_indonesia.pdf)
  + [Data & Code](https://github.com/nozominakajima/twocohortimpact) 
  
***  
[Levers for Learning: Relationships Between School-Level Factors and Literacy Outcomes in Low-Income Schools in Colombia.](https://doi.org/10.1086/708431)   
(with Barrera-Osorio, F., de Barros, A., Dryden-Peterson, S., Mulimbi, B., & Uccelli, P.)  
*Comparative Education Review*. 2020.

  + [Ungated version](files/colombia.pdf)

***
[Gender Gaps in Cognitive and Socio-emotional Skills in Early Primary Grades.](https://onlinelibrary.wiley.com/doi/abs/10.1111/desc.12931)    
(with Jung, H., Pradhan, M., Hasan, A., Kinnell, A., & Brinkman, S.)  
*Developmental Science*. 2019. 

  + Media coverage: [The Jakarta Post](https://www.thejakartapost.com/academia/2019/10/26/parenting-disregarded-treasure-in-education.html)   
  + [Ungated version](files/gender_indonesia.pdf)   
  + [Data & Code](https://github.com/nozominakajima/gender_indonesia) 
  
***
[Investing in School Readiness: A Comparison of Different Early Childhood Education Pathways in Rural Indonesia.](https://doi.org/10.1016/j.ijedudev.2019.05.009)   
(with Hasan, A., Jung, H., Brinkman, S., Pradhan, M., & Kinnell, A.)  
*International Journal for Educational Development*. 2019. 

  + Policy brief: [World Bank Research Digest](http://documents.worldbank.org/curated/en/897521507140394691/pdf/Research-Digest-Fall-2017.pdf)
  + Media coverage: [Education for Global Development](https://blogs.worldbank.org/education/are-all-early-childhood-education-experiences-equally-cost-effective) 
  + [Ungated version](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2843915)
  + [Data & Code](https://github.com/nozominakajima/pathways_indonesia)

***
[Introducing a Performance-Based Component Into Jakarta's School Grants: What Do We Know About Its Impact After Three Years?](https://doi.org/10.1016/j.econedurev.2018.10.005)     
(with Al-Samarrai, S., Shrestha, U., Hasan, A., Santoso, S., & Wijoyo, W. H. A.)    
*Economics of Education Review*. 2018.   

  + [Ungated version](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3057755)  

*** 
[The Role of Preschool Quality in Promoting Child Development.](https://www.tandfonline.com/doi/abs/10.1080/1350293X.2017.1331062)  
(with Brinkman, S. A., Hasan, A., Jung, H., Kinnell, A., & Pradhan, M.)  
*European Early Childhood Education Research Journal*. 2017.    

  + Media coverage: [Education for Global Development](https://blogs.worldbank.org/education/measurement-matters-preschool-quality)
  + [Ungated version](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2741184)  

*** 
 
### Other Writing

[A Practical Guide to Conducting Economic & Financial Analyses for Education Projects.](files/EFA_guidance_note.pdf)
  
  + I wrote this guidance note for large-scale education projects when I worked at the World Bank (2014-2016). 

&nbsp;

